### PR TITLE
Improvements for Brew and related fixes - v4.2.1

### PR DESCRIPTION
**Pull request by varp**
- new improved search
- new icons for Brew Formulae and Cask
- by default export PATH env variable with /usr/local/bin (mostly PHP is located here)
- fix icon loading for script filters results
- updated README.md

### CODE REVIEW

**Comment by varp** [comment]
@jeffbyrnes Hi, again. Could you also, please, pre-review this one?

**Comment by jeffbyrnes** [comment]
Sure thing! I'll take a look tomorrow.

**Review by jeffbyrnes — APPROVED** [review]

**Comment by varp** [comment]
@jeffbyrnes Great thanks

**Comment by jeffbyrnes** [comment]
@varp perhaps you could open a new PR w/ some additional instructions in the README? I’m struggling a little to figure out how this build process goes now.

**Comment by varp** [comment]
@jeffbyrnes sorry, was busy on the full time job. I'll do on this weekend

**Pull request merged**
